ALTM_SLASH_HELP 	= "help"
ALTM_SLASH_ADD 		= "add"
ALTM_SLASH_ADD_ALT 	= "alt"
ALTM_SLASH_ADD_MAIN 	= "main"
ALTM_SLASH_DEL 		= "del"
ALTM_SLASH_DEL_ALT	= "alt"
ALTM_SLASH_DEL_MAIN	= "main"
ALTM_SLASH_CHG 		= "change"
ALTM_SLASH_CHG_ALT	= "alt"
ALTM_SLASH_CHG_MAIN	= "main"
ALTM_SLASH_EMOTE	= "emote"
ALTM_SLASH_ON		= "on"
ALTM_SLASH_OFF		= "off"
ALTM_SLASH_EXTRACT	= "extract"
ALTM_SLASH_VERBOSE	= "verbose"
ALTM_SLASH_MAINON	= "mainon"
ALTM_SLASH_MAINOFF	= "mainoff"
ALTM_SLASH_QUERY	= "query"
ALTM_SLASH_INFO		= "info"
ALTM_SLASH_GUILDCHK	= "guildchk"
ALTM_SLASH_GUILDCHECK	= "guildcheck"
ALTM_SLASH_GUILD	= "guild"
ALTM_SLASH_CHECK	= "check"

ALTM_DEFAULT_MAINTAG	= "(Main)"

ALTM_MSG_VARS_LOADED	= "AltMinder Variables Loaded."
ALTM_MSG_BASE_SLASH	= "AltMinder: /altm <cmd> <args>"
ALTM_MSG_BASE_SLASH2	= "AltMinder: /altm help for help"
ALTM_MSG_CMD		= "/altm"
ALTM_MSG_HELP		= "<help>"
ALTM_MSG_ADD_MAIN	= "<add> main <name> <list>"
ALTM_MSG_ADD_ALT	= "<add> alt <alt> <main>"
ALTM_MSG_CHG_MAIN	= "<change> main <name> <new>"
ALTM_MSG_CHG_ALT	= "<change> alt <name> <new>"
ALTM_MSG_DEL		= "<del> <main|alt> <name>"
ALTM_MSG_ONOFF		= "<on|off>"
ALTM_MSG_EMOTE		= "<emote> <on|off>"
ALTM_MSG_EXTRACT	= "<extract> <guild> <verbose>"
ALTM_MSG_MAIN_ON	= "<mainon> <main-tag>"
ALTM_MSG_MAIN_OFF	= "<mainoff>"
ALTM_MSG_QUERY		= "A query requires a name"

ALTM_MSG_DEL_MAIN	= "del main <name>"
ALTM_MSG_DEL_ALT	= "del alt <name>"
ALTM_MSG_NEED_MAIN_NAME	= "name of main must be provided"
ALTM_MSG_NEED_BOTHNAMES	= "name of alt and main must be provided"
ALTM_MSG_MAIN_NOT_FOUND	= "was not found as a main in AltMinder."
ALTM_MSG_TRY_MAIN	= "Try /altm add main "
ALTM_MSG_UNKNOWN_COMMAND= "Unknown command:"
ALTM_MSG_EXTRACT_VRBOP	= "verbose is optional, turns on alt/main additions"
ALTM_MSG_EXTRACT_BEGIN	= "Beginning the Extraction Process."
ALTM_MSG_EXTRACT_END	= "Extraction Process is now complete."

ALTM_MSG_OUT_ADD_MAIN	= " has been added as a main"
ALTM_MSG_OUT_ADD_ALT	= " has been added as an alt of "

ALTM_MSG_OUT_DEL_MAIN	= " has been removed as a main"
ALTM_MSG_OUT_DEL_ALT	= " has been removed as an alt"

ALTM_MSG_OUT_CHG_NAME	= " has been changed to "

ALTM_MSG_OUT_EMOTE_NO	= "Emotes are not being modified."
ALTM_MSG_OUT_EMOTE_YES	= "Emotes are being modified."
ALTM_MSG_OUT_EMOTE_UNK	= "Emotes state is unknown"

ALTM_MSG_OFF		= "Messages will no longer be changed."
ALTM_MSG_ON		= "Messages will now be changed."

ALTM_MSG_OUT_MAIN_ON	= "Messages from mains will now be tagged"
ALTM_MSG_OUT_MAIN_OFF	= "Messages from mains will not be tagged"
ALTM_MSG_OUT_MAIN_SET	= "The new (MAIN) tag will be:"
